apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
  labels:
    app: nexus
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
    - name: docker-registry
      port: 8082
      targetPort: 8082
      nodePort: 30082