apiVersion: v1
kind: Service
metadata:
  name: simple-springboot-webapp
  namespace: springboot-app
  labels:
    app: simple-springboot-webapp
spec:
  type: NodePort
  selector:
    app: simple-springboot-webapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080