apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-springboot-webapp
  namespace: springboot-app
  labels:
    app: simple-springboot-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-springboot-webapp
  template:
    metadata:
      labels:
        app: simple-springboot-webapp
    spec:
      containers:
        - name: springboot-app
          image: 152.53.145.17:30082/simple-springboot-webapp:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3