apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  labels:
    app: jenkins
spec:
  project: default
  source:
    repoURL: 'https://github.com/AdnanAlagic/gitops-practice'
    path: jenkins
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3