apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
  labels:
    app: nexus
spec:
  project: default
  source:
    repoURL: 'https://github.com/AdnanAlagic/gitops-practice'
    path: nexus
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3