apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-webapp
  namespace: argocd
  labels:
    app: springboot-webapp
  annotations:
    argocd-image-updater.argoproj.io/image-list: springboot-app=152.53.145.17:30082/simple-springboot-webapp
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

    argocd-image-updater.argoproj.io/springboot-app.allow-tags: regexp:^[0-9]+$
    argocd-image-updater.argoproj.io/springboot-app.update-strategy: latest

    argocd-image-updater.argoproj.io/springboot-app.pull-secret: nexus-registry-secret
spec:
  project: default
  source:
    repoURL: 'https://github.com/AdnanAlagic/gitops-practice'
    path: springboot-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: springboot-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3