stage('Package & Deploy') {
    steps {
        dir('app') {
            sh '''
                apt-get update && apt-get install -y buildah

                echo "admin123" | buildah login --username admin --password-stdin ${NEXUS_URL}
                buildah bud --isolation=chroot -t ${NEXUS_URL}/${IMAGE_NAME}:${IMAGE_TAG} .

                buildah push --tls-verify=false ${NEXUS_URL}/${IMAGE_NAME}:${IMAGE_TAG}
                buildah tag ${NEXUS_URL}/${IMAGE_NAME}:${IMAGE_TAG} ${NEXUS_URL}/${IMAGE_NAME}:latest
                buildah push --tls-verify=false ${NEXUS_URL}/${IMAGE_NAME}:latest
            '''
        }
    }
}