apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;
    
        upstream jenkins {
            server jenkins-service.jenkins.svc.cluster.local:8080;
        }
    
        upstream kimai {
            server kimai-service.kimai.svc.cluster.local:8001;
        }
    
        server {
            listen 80;
            server_name localhost;
    
            location / {
                return 200 '<html><body><h1>Welcome to K8s Services</h1><p><a href="/jenkins/">Jenkins</a></p><p><a href="/kimai/">Kimai Time Tracking</a></p></body></html>';
                add_header Content-Type text/html;
            }
    
            location /jenkins/ {
                proxy_pass http://jenkins/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_redirect http:// $scheme://;
            }
    
            location /kimai/ {
                proxy_pass http://kimai/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_redirect http:// $scheme://;
            }
        }
    }