apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream jenkins {
            server jenkins-service.jenkins.svc.cluster.local:8080;
        }
    
        upstream kimai {
            server kimai-service.kimai.svc.cluster.local:8001;
        }
    
        upstream argocd {
            server argocd-server-nodeport.argocd.svc.cluster.local:8080;
        }
    
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
    
        # Jenkins proxy
        server {
            listen 80;
            server_name jenkins.local;
    
            client_max_body_size 50M;
    
            location / {
                proxy_pass http://jenkins;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
    
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Host $server_name;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
    
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }
        }
    
        # Kimai proxy
        server {
            listen 80;
            server_name kimai.local;
    
            location / {
                proxy_pass http://kimai;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
            }
        }
    
        # ArgoCD proxy
        server {
            listen 80;
            server_name argocd.local;
    
            location / {
                proxy_pass http://argocd;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
    
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
        }
    
        # Default server (fallback)
        server {
            listen 80 default_server;
            server_name _;
    
            location / {
                return 200 '
                <!DOCTYPE html>
                <html>
                <head><title>DevOps Dashboard</title></head>
                <body style="font-family: Arial, sans-serif; margin: 40px;">
                    <h1>DevOps Services</h1>
                    <ul style="font-size: 18px;">
                        <li><a href="http://jenkins.local">Jenkins CI/CD</a></li>
                        <li><a href="http://kimai.local">Kimai Time Tracking</a></li>
                        <li><a href="http://argocd.local">ArgoCD GitOps</a></li>
                    </ul>
                </body>
                </html>';
                add_header Content-Type text/html;
            }
        }
    }