apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 30443
      protocol: TCP
    - name: grpc
      port: 443
      targetPort: 8080
      nodePort: 30444
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server