apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  log.level: "debug"
  registries.conf: |
    registries:
    - name: nexus
      prefix: 152.53.145.17:30082
      api_url: http://152.53.145.17:30082
      ping: yes
      insecure: yes