apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false"
            - name: JENKINS_ADMIN_ID
              valueFrom:
                secretKeyRef:
                  name: jenkins-admin
                  key: username
            - name: JENKINS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins-admin
                  key: password
          volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home
            - name: containers-storage
              mountPath: /var/lib/containers
            - name: containers-config
              mountPath: /etc/containers
              readOnly: true
      volumes:
        - name: jenkins-storage
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: containers-storage
          emptyDir: {}
        - name: containers-config
          hostPath:
            path: /etc/containers
            type: Directory