apiVersion: v1
kind: Service
metadata:
  name: kimai-service
  namespace: kimai
  labels:
    app: kimai
spec:
  selector:
    app: kimai
  ports:
    - port: 8001
      targetPort: 8001
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: kimai-nodeport
  namespace: kimai
  labels:
    app: kimai
spec:
  type: NodePort
  selector:
    app: kimai
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30081
      name: http