apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kimai
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: "kimai"
            - name: MYSQL_USER
              value: "kimai"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          args:
            - "--default-authentication-plugin=mysql_native_password"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc