apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kimai-ingress
  namespace: kimai
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /kimai(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kimai-service
                port:
                  number: 8001